name: Arrows4Players 
version: 1.18.2
description: Arrows from any source can be picked up to be reused now. Oh yeah..
api-version: 1.18
author: Sycholic
website: http://www.spigotmc.org/members/sycholic.40800/
main: com.sycholic.arrows4players.PoachArrows
database: false

